/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RequestQuoteRouteImport } from './routes/request-quote'
import { Route as RepairBodyShopsRouteImport } from './routes/repair-body-shops'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as IndividualCustomersRouteImport } from './routes/individual-customers'
import { Route as ForShopsRouteImport } from './routes/for-shops'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WholesaleIndexRouteImport } from './routes/wholesale.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as WholesaleSignInRouteImport } from './routes/wholesale.sign-in'
import { Route as WholesaleApplyRouteImport } from './routes/wholesale.apply'
import { Route as QuoteIdRouteImport } from './routes/quote.$id'
import { Route as PortalSplatRouteImport } from './routes/portal_.$'
import { Route as AuthResetPasswordRouteImport } from './routes/auth.reset-password'
import { Route as AdminWholesaleQuotesRouteImport } from './routes/admin.wholesale-quotes'
import { Route as AdminWholesaleApplicationsRouteImport } from './routes/admin.wholesale-applications'
import { Route as AdminSignInRouteImport } from './routes/admin.sign-in'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminQuotesOrdersRouteImport } from './routes/admin.quotes-orders'
import { Route as AdminDeliveriesRouteImport } from './routes/admin.deliveries'
import { Route as AdminAccountsRouteImport } from './routes/admin.accounts'
import { Route as AdminWholesaleApplicationsIndexRouteImport } from './routes/admin.wholesale-applications.index'
import { Route as AdminWholesaleApplicationsIdRouteImport } from './routes/admin.wholesale-applications.$id'
import { Route as AdminRequestsIdRouteImport } from './routes/admin.requests.$id'
import { Route as AuthenticatedWholesaleDashboardRouteImport } from './routes/_authenticated/wholesale.dashboard'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestQuoteRoute = RequestQuoteRouteImport.update({
  id: '/request-quote',
  path: '/request-quote',
  getParentRoute: () => rootRouteImport,
} as any)
const RepairBodyShopsRoute = RepairBodyShopsRouteImport.update({
  id: '/repair-body-shops',
  path: '/repair-body-shops',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const IndividualCustomersRoute = IndividualCustomersRouteImport.update({
  id: '/individual-customers',
  path: '/individual-customers',
  getParentRoute: () => rootRouteImport,
} as any)
const ForShopsRoute = ForShopsRouteImport.update({
  id: '/for-shops',
  path: '/for-shops',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WholesaleIndexRoute = WholesaleIndexRouteImport.update({
  id: '/wholesale/',
  path: '/wholesale/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const WholesaleSignInRoute = WholesaleSignInRouteImport.update({
  id: '/wholesale/sign-in',
  path: '/wholesale/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const WholesaleApplyRoute = WholesaleApplyRouteImport.update({
  id: '/wholesale/apply',
  path: '/wholesale/apply',
  getParentRoute: () => rootRouteImport,
} as any)
const QuoteIdRoute = QuoteIdRouteImport.update({
  id: '/quote/$id',
  path: '/quote/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalSplatRoute = PortalSplatRouteImport.update({
  id: '/portal_/$',
  path: '/portal/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRoute,
} as any)
const AdminWholesaleQuotesRoute = AdminWholesaleQuotesRouteImport.update({
  id: '/wholesale-quotes',
  path: '/wholesale-quotes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminWholesaleApplicationsRoute =
  AdminWholesaleApplicationsRouteImport.update({
    id: '/wholesale-applications',
    path: '/wholesale-applications',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminSignInRoute = AdminSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminQuotesOrdersRoute = AdminQuotesOrdersRouteImport.update({
  id: '/quotes-orders',
  path: '/quotes-orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDeliveriesRoute = AdminDeliveriesRouteImport.update({
  id: '/deliveries',
  path: '/deliveries',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAccountsRoute = AdminAccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => AdminRoute,
} as any)
const AdminWholesaleApplicationsIndexRoute =
  AdminWholesaleApplicationsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AdminWholesaleApplicationsRoute,
  } as any)
const AdminWholesaleApplicationsIdRoute =
  AdminWholesaleApplicationsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AdminWholesaleApplicationsRoute,
  } as any)
const AdminRequestsIdRoute = AdminRequestsIdRouteImport.update({
  id: '/requests/$id',
  path: '/requests/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AuthenticatedWholesaleDashboardRoute =
  AuthenticatedWholesaleDashboardRouteImport.update({
    id: '/wholesale/dashboard',
    path: '/wholesale/dashboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/for-shops': typeof ForShopsRoute
  '/individual-customers': typeof IndividualCustomersRoute
  '/portal': typeof PortalRoute
  '/privacy': typeof PrivacyRoute
  '/repair-body-shops': typeof RepairBodyShopsRoute
  '/request-quote': typeof RequestQuoteRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/admin/accounts': typeof AdminAccountsRoute
  '/admin/deliveries': typeof AdminDeliveriesRoute
  '/admin/quotes-orders': typeof AdminQuotesOrdersRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/sign-in': typeof AdminSignInRoute
  '/admin/wholesale-applications': typeof AdminWholesaleApplicationsRouteWithChildren
  '/admin/wholesale-quotes': typeof AdminWholesaleQuotesRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/portal/$': typeof PortalSplatRoute
  '/quote/$id': typeof QuoteIdRoute
  '/wholesale/apply': typeof WholesaleApplyRoute
  '/wholesale/sign-in': typeof WholesaleSignInRoute
  '/admin/': typeof AdminIndexRoute
  '/wholesale/': typeof WholesaleIndexRoute
  '/wholesale/dashboard': typeof AuthenticatedWholesaleDashboardRoute
  '/admin/requests/$id': typeof AdminRequestsIdRoute
  '/admin/wholesale-applications/$id': typeof AdminWholesaleApplicationsIdRoute
  '/admin/wholesale-applications/': typeof AdminWholesaleApplicationsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRouteWithChildren
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/for-shops': typeof ForShopsRoute
  '/individual-customers': typeof IndividualCustomersRoute
  '/portal': typeof PortalRoute
  '/privacy': typeof PrivacyRoute
  '/repair-body-shops': typeof RepairBodyShopsRoute
  '/request-quote': typeof RequestQuoteRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/admin/accounts': typeof AdminAccountsRoute
  '/admin/deliveries': typeof AdminDeliveriesRoute
  '/admin/quotes-orders': typeof AdminQuotesOrdersRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/sign-in': typeof AdminSignInRoute
  '/admin/wholesale-quotes': typeof AdminWholesaleQuotesRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/portal/$': typeof PortalSplatRoute
  '/quote/$id': typeof QuoteIdRoute
  '/wholesale/apply': typeof WholesaleApplyRoute
  '/wholesale/sign-in': typeof WholesaleSignInRoute
  '/admin': typeof AdminIndexRoute
  '/wholesale': typeof WholesaleIndexRoute
  '/wholesale/dashboard': typeof AuthenticatedWholesaleDashboardRoute
  '/admin/requests/$id': typeof AdminRequestsIdRoute
  '/admin/wholesale-applications/$id': typeof AdminWholesaleApplicationsIdRoute
  '/admin/wholesale-applications': typeof AdminWholesaleApplicationsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/for-shops': typeof ForShopsRoute
  '/individual-customers': typeof IndividualCustomersRoute
  '/portal': typeof PortalRoute
  '/privacy': typeof PrivacyRoute
  '/repair-body-shops': typeof RepairBodyShopsRoute
  '/request-quote': typeof RequestQuoteRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/admin/accounts': typeof AdminAccountsRoute
  '/admin/deliveries': typeof AdminDeliveriesRoute
  '/admin/quotes-orders': typeof AdminQuotesOrdersRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/sign-in': typeof AdminSignInRoute
  '/admin/wholesale-applications': typeof AdminWholesaleApplicationsRouteWithChildren
  '/admin/wholesale-quotes': typeof AdminWholesaleQuotesRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/portal_/$': typeof PortalSplatRoute
  '/quote/$id': typeof QuoteIdRoute
  '/wholesale/apply': typeof WholesaleApplyRoute
  '/wholesale/sign-in': typeof WholesaleSignInRoute
  '/admin/': typeof AdminIndexRoute
  '/wholesale/': typeof WholesaleIndexRoute
  '/_authenticated/wholesale/dashboard': typeof AuthenticatedWholesaleDashboardRoute
  '/admin/requests/$id': typeof AdminRequestsIdRoute
  '/admin/wholesale-applications/$id': typeof AdminWholesaleApplicationsIdRoute
  '/admin/wholesale-applications/': typeof AdminWholesaleApplicationsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/auth'
    | '/contact'
    | '/faq'
    | '/for-shops'
    | '/individual-customers'
    | '/portal'
    | '/privacy'
    | '/repair-body-shops'
    | '/request-quote'
    | '/sitemap.xml'
    | '/terms'
    | '/admin/accounts'
    | '/admin/deliveries'
    | '/admin/quotes-orders'
    | '/admin/settings'
    | '/admin/sign-in'
    | '/admin/wholesale-applications'
    | '/admin/wholesale-quotes'
    | '/auth/reset-password'
    | '/portal/$'
    | '/quote/$id'
    | '/wholesale/apply'
    | '/wholesale/sign-in'
    | '/admin/'
    | '/wholesale/'
    | '/wholesale/dashboard'
    | '/admin/requests/$id'
    | '/admin/wholesale-applications/$id'
    | '/admin/wholesale-applications/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/faq'
    | '/for-shops'
    | '/individual-customers'
    | '/portal'
    | '/privacy'
    | '/repair-body-shops'
    | '/request-quote'
    | '/sitemap.xml'
    | '/terms'
    | '/admin/accounts'
    | '/admin/deliveries'
    | '/admin/quotes-orders'
    | '/admin/settings'
    | '/admin/sign-in'
    | '/admin/wholesale-quotes'
    | '/auth/reset-password'
    | '/portal/$'
    | '/quote/$id'
    | '/wholesale/apply'
    | '/wholesale/sign-in'
    | '/admin'
    | '/wholesale'
    | '/wholesale/dashboard'
    | '/admin/requests/$id'
    | '/admin/wholesale-applications/$id'
    | '/admin/wholesale-applications'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/admin'
    | '/auth'
    | '/contact'
    | '/faq'
    | '/for-shops'
    | '/individual-customers'
    | '/portal'
    | '/privacy'
    | '/repair-body-shops'
    | '/request-quote'
    | '/sitemap.xml'
    | '/terms'
    | '/admin/accounts'
    | '/admin/deliveries'
    | '/admin/quotes-orders'
    | '/admin/settings'
    | '/admin/sign-in'
    | '/admin/wholesale-applications'
    | '/admin/wholesale-quotes'
    | '/auth/reset-password'
    | '/portal_/$'
    | '/quote/$id'
    | '/wholesale/apply'
    | '/wholesale/sign-in'
    | '/admin/'
    | '/wholesale/'
    | '/_authenticated/wholesale/dashboard'
    | '/admin/requests/$id'
    | '/admin/wholesale-applications/$id'
    | '/admin/wholesale-applications/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  ForShopsRoute: typeof ForShopsRoute
  IndividualCustomersRoute: typeof IndividualCustomersRoute
  PortalRoute: typeof PortalRoute
  PrivacyRoute: typeof PrivacyRoute
  RepairBodyShopsRoute: typeof RepairBodyShopsRoute
  RequestQuoteRoute: typeof RequestQuoteRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  PortalSplatRoute: typeof PortalSplatRoute
  QuoteIdRoute: typeof QuoteIdRoute
  WholesaleApplyRoute: typeof WholesaleApplyRoute
  WholesaleSignInRoute: typeof WholesaleSignInRoute
  WholesaleIndexRoute: typeof WholesaleIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/request-quote': {
      id: '/request-quote'
      path: '/request-quote'
      fullPath: '/request-quote'
      preLoaderRoute: typeof RequestQuoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repair-body-shops': {
      id: '/repair-body-shops'
      path: '/repair-body-shops'
      fullPath: '/repair-body-shops'
      preLoaderRoute: typeof RepairBodyShopsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/individual-customers': {
      id: '/individual-customers'
      path: '/individual-customers'
      fullPath: '/individual-customers'
      preLoaderRoute: typeof IndividualCustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for-shops': {
      id: '/for-shops'
      path: '/for-shops'
      fullPath: '/for-shops'
      preLoaderRoute: typeof ForShopsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wholesale/': {
      id: '/wholesale/'
      path: '/wholesale'
      fullPath: '/wholesale/'
      preLoaderRoute: typeof WholesaleIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/wholesale/sign-in': {
      id: '/wholesale/sign-in'
      path: '/wholesale/sign-in'
      fullPath: '/wholesale/sign-in'
      preLoaderRoute: typeof WholesaleSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wholesale/apply': {
      id: '/wholesale/apply'
      path: '/wholesale/apply'
      fullPath: '/wholesale/apply'
      preLoaderRoute: typeof WholesaleApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quote/$id': {
      id: '/quote/$id'
      path: '/quote/$id'
      fullPath: '/quote/$id'
      preLoaderRoute: typeof QuoteIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal_/$': {
      id: '/portal_/$'
      path: '/portal/$'
      fullPath: '/portal/$'
      preLoaderRoute: typeof PortalSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/admin/wholesale-quotes': {
      id: '/admin/wholesale-quotes'
      path: '/wholesale-quotes'
      fullPath: '/admin/wholesale-quotes'
      preLoaderRoute: typeof AdminWholesaleQuotesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/wholesale-applications': {
      id: '/admin/wholesale-applications'
      path: '/wholesale-applications'
      fullPath: '/admin/wholesale-applications'
      preLoaderRoute: typeof AdminWholesaleApplicationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/sign-in': {
      id: '/admin/sign-in'
      path: '/sign-in'
      fullPath: '/admin/sign-in'
      preLoaderRoute: typeof AdminSignInRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/quotes-orders': {
      id: '/admin/quotes-orders'
      path: '/quotes-orders'
      fullPath: '/admin/quotes-orders'
      preLoaderRoute: typeof AdminQuotesOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/deliveries': {
      id: '/admin/deliveries'
      path: '/deliveries'
      fullPath: '/admin/deliveries'
      preLoaderRoute: typeof AdminDeliveriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/accounts': {
      id: '/admin/accounts'
      path: '/accounts'
      fullPath: '/admin/accounts'
      preLoaderRoute: typeof AdminAccountsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/wholesale-applications/': {
      id: '/admin/wholesale-applications/'
      path: '/'
      fullPath: '/admin/wholesale-applications/'
      preLoaderRoute: typeof AdminWholesaleApplicationsIndexRouteImport
      parentRoute: typeof AdminWholesaleApplicationsRoute
    }
    '/admin/wholesale-applications/$id': {
      id: '/admin/wholesale-applications/$id'
      path: '/$id'
      fullPath: '/admin/wholesale-applications/$id'
      preLoaderRoute: typeof AdminWholesaleApplicationsIdRouteImport
      parentRoute: typeof AdminWholesaleApplicationsRoute
    }
    '/admin/requests/$id': {
      id: '/admin/requests/$id'
      path: '/requests/$id'
      fullPath: '/admin/requests/$id'
      preLoaderRoute: typeof AdminRequestsIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_authenticated/wholesale/dashboard': {
      id: '/_authenticated/wholesale/dashboard'
      path: '/wholesale/dashboard'
      fullPath: '/wholesale/dashboard'
      preLoaderRoute: typeof AuthenticatedWholesaleDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedWholesaleDashboardRoute: typeof AuthenticatedWholesaleDashboardRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedWholesaleDashboardRoute: AuthenticatedWholesaleDashboardRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AdminWholesaleApplicationsRouteChildren {
  AdminWholesaleApplicationsIdRoute: typeof AdminWholesaleApplicationsIdRoute
  AdminWholesaleApplicationsIndexRoute: typeof AdminWholesaleApplicationsIndexRoute
}

const AdminWholesaleApplicationsRouteChildren: AdminWholesaleApplicationsRouteChildren =
  {
    AdminWholesaleApplicationsIdRoute: AdminWholesaleApplicationsIdRoute,
    AdminWholesaleApplicationsIndexRoute: AdminWholesaleApplicationsIndexRoute,
  }

const AdminWholesaleApplicationsRouteWithChildren =
  AdminWholesaleApplicationsRoute._addFileChildren(
    AdminWholesaleApplicationsRouteChildren,
  )

interface AdminRouteChildren {
  AdminAccountsRoute: typeof AdminAccountsRoute
  AdminDeliveriesRoute: typeof AdminDeliveriesRoute
  AdminQuotesOrdersRoute: typeof AdminQuotesOrdersRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminSignInRoute: typeof AdminSignInRoute
  AdminWholesaleApplicationsRoute: typeof AdminWholesaleApplicationsRouteWithChildren
  AdminWholesaleQuotesRoute: typeof AdminWholesaleQuotesRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminRequestsIdRoute: typeof AdminRequestsIdRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAccountsRoute: AdminAccountsRoute,
  AdminDeliveriesRoute: AdminDeliveriesRoute,
  AdminQuotesOrdersRoute: AdminQuotesOrdersRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminSignInRoute: AdminSignInRoute,
  AdminWholesaleApplicationsRoute: AdminWholesaleApplicationsRouteWithChildren,
  AdminWholesaleQuotesRoute: AdminWholesaleQuotesRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminRequestsIdRoute: AdminRequestsIdRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AuthRouteChildren {
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthResetPasswordRoute: AuthResetPasswordRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  ForShopsRoute: ForShopsRoute,
  IndividualCustomersRoute: IndividualCustomersRoute,
  PortalRoute: PortalRoute,
  PrivacyRoute: PrivacyRoute,
  RepairBodyShopsRoute: RepairBodyShopsRoute,
  RequestQuoteRoute: RequestQuoteRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  PortalSplatRoute: PortalSplatRoute,
  QuoteIdRoute: QuoteIdRoute,
  WholesaleApplyRoute: WholesaleApplyRoute,
  WholesaleSignInRoute: WholesaleSignInRoute,
  WholesaleIndexRoute: WholesaleIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
