/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RequestQuoteRouteImport } from './routes/request-quote'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as ForShopsRouteImport } from './routes/for-shops'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WholesaleIndexRouteImport } from './routes/wholesale.index'
import { Route as PortalIndexRouteImport } from './routes/portal.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as WholesaleApplyRouteImport } from './routes/wholesale.apply'
import { Route as QuoteIdRouteImport } from './routes/quote.$id'
import { Route as PortalRequestRouteImport } from './routes/portal.request'
import { Route as PortalProfileRouteImport } from './routes/portal.profile'
import { Route as PortalHistoryRouteImport } from './routes/portal.history'
import { Route as AuthResetPasswordRouteImport } from './routes/auth.reset-password'
import { Route as AdminWholesaleApplicationsRouteImport } from './routes/admin.wholesale-applications'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminDeliveriesRouteImport } from './routes/admin.deliveries'
import { Route as AdminAccountsRouteImport } from './routes/admin.accounts'
import { Route as AdminRequestsIdRouteImport } from './routes/admin.requests.$id'
import { Route as AuthenticatedWholesaleDashboardRouteImport } from './routes/_authenticated/wholesale.dashboard'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestQuoteRoute = RequestQuoteRouteImport.update({
  id: '/request-quote',
  path: '/request-quote',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const ForShopsRoute = ForShopsRouteImport.update({
  id: '/for-shops',
  path: '/for-shops',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WholesaleIndexRoute = WholesaleIndexRouteImport.update({
  id: '/wholesale/',
  path: '/wholesale/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalIndexRoute = PortalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortalRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const WholesaleApplyRoute = WholesaleApplyRouteImport.update({
  id: '/wholesale/apply',
  path: '/wholesale/apply',
  getParentRoute: () => rootRouteImport,
} as any)
const QuoteIdRoute = QuoteIdRouteImport.update({
  id: '/quote/$id',
  path: '/quote/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRequestRoute = PortalRequestRouteImport.update({
  id: '/request',
  path: '/request',
  getParentRoute: () => PortalRoute,
} as any)
const PortalProfileRoute = PortalProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => PortalRoute,
} as any)
const PortalHistoryRoute = PortalHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => PortalRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRoute,
} as any)
const AdminWholesaleApplicationsRoute =
  AdminWholesaleApplicationsRouteImport.update({
    id: '/wholesale-applications',
    path: '/wholesale-applications',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDeliveriesRoute = AdminDeliveriesRouteImport.update({
  id: '/deliveries',
  path: '/deliveries',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAccountsRoute = AdminAccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRequestsIdRoute = AdminRequestsIdRouteImport.update({
  id: '/requests/$id',
  path: '/requests/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AuthenticatedWholesaleDashboardRoute =
  AuthenticatedWholesaleDashboardRouteImport.update({
    id: '/wholesale/dashboard',
    path: '/wholesale/dashboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/for-shops': typeof ForShopsRoute
  '/portal': typeof PortalRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/request-quote': typeof RequestQuoteRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/admin/accounts': typeof AdminAccountsRoute
  '/admin/deliveries': typeof AdminDeliveriesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/wholesale-applications': typeof AdminWholesaleApplicationsRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/portal/history': typeof PortalHistoryRoute
  '/portal/profile': typeof PortalProfileRoute
  '/portal/request': typeof PortalRequestRoute
  '/quote/$id': typeof QuoteIdRoute
  '/wholesale/apply': typeof WholesaleApplyRoute
  '/admin/': typeof AdminIndexRoute
  '/portal/': typeof PortalIndexRoute
  '/wholesale/': typeof WholesaleIndexRoute
  '/wholesale/dashboard': typeof AuthenticatedWholesaleDashboardRoute
  '/admin/requests/$id': typeof AdminRequestsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRouteWithChildren
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/for-shops': typeof ForShopsRoute
  '/privacy': typeof PrivacyRoute
  '/request-quote': typeof RequestQuoteRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/admin/accounts': typeof AdminAccountsRoute
  '/admin/deliveries': typeof AdminDeliveriesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/wholesale-applications': typeof AdminWholesaleApplicationsRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/portal/history': typeof PortalHistoryRoute
  '/portal/profile': typeof PortalProfileRoute
  '/portal/request': typeof PortalRequestRoute
  '/quote/$id': typeof QuoteIdRoute
  '/wholesale/apply': typeof WholesaleApplyRoute
  '/admin': typeof AdminIndexRoute
  '/portal': typeof PortalIndexRoute
  '/wholesale': typeof WholesaleIndexRoute
  '/wholesale/dashboard': typeof AuthenticatedWholesaleDashboardRoute
  '/admin/requests/$id': typeof AdminRequestsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/for-shops': typeof ForShopsRoute
  '/portal': typeof PortalRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/request-quote': typeof RequestQuoteRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/admin/accounts': typeof AdminAccountsRoute
  '/admin/deliveries': typeof AdminDeliveriesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/wholesale-applications': typeof AdminWholesaleApplicationsRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/portal/history': typeof PortalHistoryRoute
  '/portal/profile': typeof PortalProfileRoute
  '/portal/request': typeof PortalRequestRoute
  '/quote/$id': typeof QuoteIdRoute
  '/wholesale/apply': typeof WholesaleApplyRoute
  '/admin/': typeof AdminIndexRoute
  '/portal/': typeof PortalIndexRoute
  '/wholesale/': typeof WholesaleIndexRoute
  '/_authenticated/wholesale/dashboard': typeof AuthenticatedWholesaleDashboardRoute
  '/admin/requests/$id': typeof AdminRequestsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/auth'
    | '/contact'
    | '/faq'
    | '/for-shops'
    | '/portal'
    | '/privacy'
    | '/request-quote'
    | '/sitemap.xml'
    | '/terms'
    | '/admin/accounts'
    | '/admin/deliveries'
    | '/admin/settings'
    | '/admin/wholesale-applications'
    | '/auth/reset-password'
    | '/portal/history'
    | '/portal/profile'
    | '/portal/request'
    | '/quote/$id'
    | '/wholesale/apply'
    | '/admin/'
    | '/portal/'
    | '/wholesale/'
    | '/wholesale/dashboard'
    | '/admin/requests/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/faq'
    | '/for-shops'
    | '/privacy'
    | '/request-quote'
    | '/sitemap.xml'
    | '/terms'
    | '/admin/accounts'
    | '/admin/deliveries'
    | '/admin/settings'
    | '/admin/wholesale-applications'
    | '/auth/reset-password'
    | '/portal/history'
    | '/portal/profile'
    | '/portal/request'
    | '/quote/$id'
    | '/wholesale/apply'
    | '/admin'
    | '/portal'
    | '/wholesale'
    | '/wholesale/dashboard'
    | '/admin/requests/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/admin'
    | '/auth'
    | '/contact'
    | '/faq'
    | '/for-shops'
    | '/portal'
    | '/privacy'
    | '/request-quote'
    | '/sitemap.xml'
    | '/terms'
    | '/admin/accounts'
    | '/admin/deliveries'
    | '/admin/settings'
    | '/admin/wholesale-applications'
    | '/auth/reset-password'
    | '/portal/history'
    | '/portal/profile'
    | '/portal/request'
    | '/quote/$id'
    | '/wholesale/apply'
    | '/admin/'
    | '/portal/'
    | '/wholesale/'
    | '/_authenticated/wholesale/dashboard'
    | '/admin/requests/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  ForShopsRoute: typeof ForShopsRoute
  PortalRoute: typeof PortalRouteWithChildren
  PrivacyRoute: typeof PrivacyRoute
  RequestQuoteRoute: typeof RequestQuoteRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  QuoteIdRoute: typeof QuoteIdRoute
  WholesaleApplyRoute: typeof WholesaleApplyRoute
  WholesaleIndexRoute: typeof WholesaleIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/request-quote': {
      id: '/request-quote'
      path: '/request-quote'
      fullPath: '/request-quote'
      preLoaderRoute: typeof RequestQuoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for-shops': {
      id: '/for-shops'
      path: '/for-shops'
      fullPath: '/for-shops'
      preLoaderRoute: typeof ForShopsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wholesale/': {
      id: '/wholesale/'
      path: '/wholesale'
      fullPath: '/wholesale/'
      preLoaderRoute: typeof WholesaleIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/': {
      id: '/portal/'
      path: '/'
      fullPath: '/portal/'
      preLoaderRoute: typeof PortalIndexRouteImport
      parentRoute: typeof PortalRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/wholesale/apply': {
      id: '/wholesale/apply'
      path: '/wholesale/apply'
      fullPath: '/wholesale/apply'
      preLoaderRoute: typeof WholesaleApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quote/$id': {
      id: '/quote/$id'
      path: '/quote/$id'
      fullPath: '/quote/$id'
      preLoaderRoute: typeof QuoteIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/request': {
      id: '/portal/request'
      path: '/request'
      fullPath: '/portal/request'
      preLoaderRoute: typeof PortalRequestRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/profile': {
      id: '/portal/profile'
      path: '/profile'
      fullPath: '/portal/profile'
      preLoaderRoute: typeof PortalProfileRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/history': {
      id: '/portal/history'
      path: '/history'
      fullPath: '/portal/history'
      preLoaderRoute: typeof PortalHistoryRouteImport
      parentRoute: typeof PortalRoute
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/admin/wholesale-applications': {
      id: '/admin/wholesale-applications'
      path: '/wholesale-applications'
      fullPath: '/admin/wholesale-applications'
      preLoaderRoute: typeof AdminWholesaleApplicationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/deliveries': {
      id: '/admin/deliveries'
      path: '/deliveries'
      fullPath: '/admin/deliveries'
      preLoaderRoute: typeof AdminDeliveriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/accounts': {
      id: '/admin/accounts'
      path: '/accounts'
      fullPath: '/admin/accounts'
      preLoaderRoute: typeof AdminAccountsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/requests/$id': {
      id: '/admin/requests/$id'
      path: '/requests/$id'
      fullPath: '/admin/requests/$id'
      preLoaderRoute: typeof AdminRequestsIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_authenticated/wholesale/dashboard': {
      id: '/_authenticated/wholesale/dashboard'
      path: '/wholesale/dashboard'
      fullPath: '/wholesale/dashboard'
      preLoaderRoute: typeof AuthenticatedWholesaleDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedWholesaleDashboardRoute: typeof AuthenticatedWholesaleDashboardRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedWholesaleDashboardRoute: AuthenticatedWholesaleDashboardRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AdminRouteChildren {
  AdminAccountsRoute: typeof AdminAccountsRoute
  AdminDeliveriesRoute: typeof AdminDeliveriesRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminWholesaleApplicationsRoute: typeof AdminWholesaleApplicationsRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminRequestsIdRoute: typeof AdminRequestsIdRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAccountsRoute: AdminAccountsRoute,
  AdminDeliveriesRoute: AdminDeliveriesRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminWholesaleApplicationsRoute: AdminWholesaleApplicationsRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminRequestsIdRoute: AdminRequestsIdRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AuthRouteChildren {
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthResetPasswordRoute: AuthResetPasswordRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface PortalRouteChildren {
  PortalHistoryRoute: typeof PortalHistoryRoute
  PortalProfileRoute: typeof PortalProfileRoute
  PortalRequestRoute: typeof PortalRequestRoute
  PortalIndexRoute: typeof PortalIndexRoute
}

const PortalRouteChildren: PortalRouteChildren = {
  PortalHistoryRoute: PortalHistoryRoute,
  PortalProfileRoute: PortalProfileRoute,
  PortalRequestRoute: PortalRequestRoute,
  PortalIndexRoute: PortalIndexRoute,
}

const PortalRouteWithChildren =
  PortalRoute._addFileChildren(PortalRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  ForShopsRoute: ForShopsRoute,
  PortalRoute: PortalRouteWithChildren,
  PrivacyRoute: PrivacyRoute,
  RequestQuoteRoute: RequestQuoteRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  QuoteIdRoute: QuoteIdRoute,
  WholesaleApplyRoute: WholesaleApplyRoute,
  WholesaleIndexRoute: WholesaleIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
